name: "[Reusable] Run tests on module"
on:
  workflow_call:
    inputs:
      module_name:
        required: true
        type: string
      os:
        required: true
        type: string
      shell:
        required: false
        type: string
        default: "pwsh"

jobs:
  test:
    name: Run Invoke-Build
    runs-on: ${{ inputs.os }}
    defaults:
      run:
        shell: ${{ inputs.shell }}
        working-directory: ${{ inputs.module_name }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install and cache PowerShell modules
        id: pscache
        uses: potatoqualitee/psmodulecache@v5.1
        with:
          modules-to-cache: Pester:5.3.3, PSSCriptAnalyzer:1.21.0, InvokeBuild:5.10.1, platyPS:0.12.0
          shell: ${{ inputs.shell }}
      - name: Display shell info
        run: |
          $esc = [char]27
          Write-Output "${esc}[90menv:PATH: ${esc}[0m${env:PATH}"
          Write-Output "${esc}[90mRunning on: ${esc}[34mPowerShell $($PSVersionTable.PSEdition) $($PSVersionTable.PSVersion)${esc}[0m ($($PSVersionTable.OS))"
          Write-Output "${esc}[90mTargetting: ${esc}[0m${{ inputs.module_name }}"
          Write-Output "${esc}[90mCurrent path: ${esc}[0m${PWD}"
      - name: Bootstrap
        run: ./actions_bootstrap.ps1
      - name: Test and Build
        run: Invoke-Build -File .\src\${{ inputs.module_name }}.build.ps1
