name: Publish
on: workflow_dispatch

jobs:
  publish:
    name: Publish on PSGallery
    runs-on: windows-latest
    strategy:
      matrix:
        package: [ExecutionSteps, ExecutionSteps-Generic]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run Publish-Module
        shell: pwsh
        env:
          NUGET_KEY: ${{ secrets.PS_GALLERY_API_KEY }}
        run: |
          cd ${{ matrix.package }}
          Publish-Module -Path . -NuGetApiKey $env:NUGET_KEY
