name: Publish
on: workflow_dispatch

jobs:
  publish:
    name: Publish on PSGallery
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [ExecutionSteps, ExecutionSteps-Generic]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run Publish-Module
        uses: pcgeek86/publish-powershell-module-action@v20
        with:
          ModulePath: ${{ matrix.package }}
          NuGetApiKey: ${{ secrets.PS_GALLERY_API_KEY }}
