name: Publish to PSGallery
on: workflow_dispatch

jobs:
  publish:
    name: Publish
    runs-on: windows-latest
    strategy:
      matrix:
        package: [ExecutionSteps, ExecutionSteps-Generic]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install and cache PowerShell modules
        id: pscache
        uses: potatoqualitee/psmodulecache@v5.1
        with:
          modules-to-cache: Pester, PSSCriptAnalyzer, InvokeBuild, platyPS
      - name: Run Publish-Module
        shell: pwsh
        run: |
          $env:PSModulePath = $env:PSModulePath+[IO.Path]::PathSeparator+$PWD
          Write-Host -ForegroundColor Blue "Working with PSModulePath $($env:PSModulePath)"
          cd ${{ matrix.package }}
          Write-Host -ForegroundColor Blue "About to publish ${{ matrix.package }} from $PWD"
          Publish-Module -Path . -NuGetApiKey ${{ secrets.PS_GALLERY_API_KEY }} -Verbose
