name: Test ExecutionSteps
on:
  push:
    paths:
      - ".github/workflows/test_ExecutionSteps.yml"
      - ".github/workflows/.reusable_Test.yml"
      - "ExecutionSteps/**"
  pull_request:
    paths:
      - ".github/workflows/test_ExecutionSteps.yml"
      - ".github/workflows/.reusable_Test.yml"
      - "ExecutionSteps/**"

jobs:
  test:
    name: Run Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        shell: [pwsh]
        include:
          - os: windows-latest
            shell: powershell
      fail-fast: false
    uses: ./.github/workflows/.reusable_Test.yml
    with:
      module_name: ExecutionSteps
      os: ${{ matrix.os }}
      shell: ${{ matrix.shell }}
